/**
 * Copyright 2017 Brian Costabile
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
/*============================================================================*/
/**
 * @file bsp_Gpio_dktm4c129x.h
 * @brief Contains Macros and defines for the GPIO block specific
 *        to the dktm4c129x platform.
 */
#pragma once

#include "inc/hw_memmap.h"
#include "inc/hw_Gpio.h"
#include "bsp_Platform.h"

#include BUILD_INCLUDE_STRING( bsp_Gpio_, PLATFORM_CORE )

/**
 * PA0 - VCP-RX
 * PA1 - VCP-TX
 * PA2 - TPA2 (J19:14)
 * PA3 - TPA3 (J19:16)
 * PA4 - TPA4 (J19:18)
 * PA5 - TPA5 (J19:20)
 * PA6 - TPA6 (J28:8)
 * PA7 - TPA7 (J27:18)
 */
#define BSP_GPIO_PORT_ID_VCP_RX    BSP_GPIO_PORT_ID_PA0
#define BSP_GPIO_BASE_ADDR_VCP_RX  BSP_GPIO_BASE_ADDR_PA0
#define BSP_GPIO_BIT_OFFSET_VCP_RX BSP_GPIO_BIT_OFFSET_PA0
#define BSP_GPIO_BIT_MASK_VCP_RX   BSP_GPIO_BIT_MASK_PA0

#define BSP_GPIO_PORT_ID_VCP_TX     BSP_GPIO_PORT_ID_PA1
#define BSP_GPIO_BASE_ADDR_VCP_TX   BSP_GPIO_BASE_ADDR_PA1
#define BSP_GPIO_BIT_OFFSET_VCP_TX  BSP_GPIO_BIT_OFFSET_PA1
#define BSP_GPIO_BIT_MASK_VCP_TX    BSP_GPIO_BIT_MASK_PA1

#define BSP_GPIO_PORT_ID_TPA2       BSP_GPIO_PORT_ID_PA2
#define BSP_GPIO_BASE_ADDR_TPA2     BSP_GPIO_BASE_ADDR_PA2
#define BSP_GPIO_BIT_OFFSET_TPA2    BSP_GPIO_BIT_OFFSET_PA2
#define BSP_GPIO_BIT_MASK_TPA2      BSP_GPIO_BIT_MASK_PA2

#define BSP_GPIO_PORT_ID_TPA3       BSP_GPIO_PORT_ID_PA3
#define BSP_GPIO_BASE_ADDR_TPA3     BSP_GPIO_BASE_ADDR_PA3
#define BSP_GPIO_BIT_OFFSET_TPA3    BSP_GPIO_BIT_OFFSET_PA3
#define BSP_GPIO_BIT_MASK_TPA3      BSP_GPIO_BIT_MASK_PA3

#define BSP_GPIO_PORT_ID_TPA4       BSP_GPIO_PORT_ID_PA4
#define BSP_GPIO_BASE_ADDR_TPA4     BSP_GPIO_BASE_ADDR_PA4
#define BSP_GPIO_BIT_OFFSET_TPA4    BSP_GPIO_BIT_OFFSET_PA4
#define BSP_GPIO_BIT_MASK_TPA4      BSP_GPIO_BIT_MASK_PA4

#define BSP_GPIO_PORT_ID_TPA5       BSP_GPIO_PORT_ID_PA5
#define BSP_GPIO_BASE_ADDR_TPA5     BSP_GPIO_BASE_ADDR_PA5
#define BSP_GPIO_BIT_OFFSET_TPA5    BSP_GPIO_BIT_OFFSET_PA5
#define BSP_GPIO_BIT_MASK_TPA5      BSP_GPIO_BIT_MASK_PA5

#define BSP_GPIO_PORT_ID_TPA6       BSP_GPIO_PORT_ID_PA6
#define BSP_GPIO_BASE_ADDR_TPA6     BSP_GPIO_BASE_ADDR_PA6
#define BSP_GPIO_BIT_OFFSET_TPA6    BSP_GPIO_BIT_OFFSET_PA6
#define BSP_GPIO_BIT_MASK_TPA6      BSP_GPIO_BIT_MASK_PA6

#define BSP_GPIO_PORT_ID_TPA7       BSP_GPIO_PORT_ID_PA7
#define BSP_GPIO_BASE_ADDR_TPA7     BSP_GPIO_BASE_ADDR_PA7
#define BSP_GPIO_BIT_OFFSET_TPA7    BSP_GPIO_BIT_OFFSET_PA7
#define BSP_GPIO_BIT_MASK_TPA7      BSP_GPIO_BIT_MASK_PA7


/**
 * PB0 - USB_ID
 * PB1 - USB_VB
 * PB2 - TPB2 (J27:25)
 * PB3 - TPB3 (J27:3)
 * PB4 - TPB4 (J29:A9)
 * PB5 - TPB5 (J6:10)
 * PB6 - TPB6 (J18) TMP100 I2C SCL
 * PB7 - TPB7 (J20) TMP100 I2C SDA
 */
#define BSP_GPIO_PORT_ID_USB_ID    BSP_GPIO_PORT_ID_PB0
#define BSP_GPIO_BASE_ADDR_USB_ID  BSP_GPIO_BASE_ADDR_PB0
#define BSP_GPIO_BIT_OFFSET_USB_ID BSP_GPIO_BIT_OFFSET_PB0
#define BSP_GPIO_BIT_MASK_USB_ID   BSP_GPIO_BIT_MASK_PB0

#define BSP_GPIO_PORT_ID_USB_VB    BSP_GPIO_PORT_ID_PB1
#define BSP_GPIO_BASE_ADDR_USB_VB  BSP_GPIO_BASE_ADDR_PB1
#define BSP_GPIO_BIT_OFFSET_USB_VB BSP_GPIO_BIT_OFFSET_PB1
#define BSP_GPIO_BIT_MASK_USB_VB   BSP_GPIO_BIT_MASK_PB1

#define BSP_GPIO_PORT_ID_TPB2      BSP_GPIO_PORT_ID_PB2
#define BSP_GPIO_BASE_ADDR_TPB2    BSP_GPIO_BASE_ADDR_PB2
#define BSP_GPIO_BIT_OFFSET_TPB2   BSP_GPIO_BIT_OFFSET_PB2
#define BSP_GPIO_BIT_MASK_TPB2     BSP_GPIO_BIT_MASK_PB2

#define BSP_GPIO_PORT_ID_TPB3      BSP_GPIO_PORT_ID_PB3
#define BSP_GPIO_BASE_ADDR_TPB3    BSP_GPIO_BASE_ADDR_PB3
#define BSP_GPIO_BIT_OFFSET_TPB3   BSP_GPIO_BIT_OFFSET_PB3
#define BSP_GPIO_BIT_MASK_TPB3     BSP_GPIO_BIT_MASK_PB3

#define BSP_GPIO_PORT_ID_TPB4      BSP_GPIO_PORT_ID_PB4
#define BSP_GPIO_BASE_ADDR_TPB4    BSP_GPIO_BASE_ADDR_PB4
#define BSP_GPIO_BIT_OFFSET_TPB4   BSP_GPIO_BIT_OFFSET_PB4
#define BSP_GPIO_BIT_MASK_TPB4     BSP_GPIO_BIT_MASK_PB4

#define BSP_GPIO_PORT_ID_TPB5      BSP_GPIO_PORT_ID_PB5
#define BSP_GPIO_BASE_ADDR_TPB5    BSP_GPIO_BASE_ADDR_PB5
#define BSP_GPIO_BIT_OFFSET_TPB5   BSP_GPIO_BIT_OFFSET_PB5
#define BSP_GPIO_BIT_MASK_TPB5     BSP_GPIO_BIT_MASK_PB5

#define BSP_GPIO_PORT_ID_TPB6      BSP_GPIO_PORT_ID_PB6
#define BSP_GPIO_BASE_ADDR_TPB6    BSP_GPIO_BASE_ADDR_PB6
#define BSP_GPIO_BIT_OFFSET_TPB6   BSP_GPIO_BIT_OFFSET_PB6
#define BSP_GPIO_BIT_MASK_TPB6     BSP_GPIO_BIT_MASK_PB6

#define BSP_GPIO_PORT_ID_TPB7      BSP_GPIO_PORT_ID_PB7
#define BSP_GPIO_BASE_ADDR_TPB7    BSP_GPIO_BASE_ADDR_PB7
#define BSP_GPIO_BIT_OFFSET_TPB7   BSP_GPIO_BIT_OFFSET_PB7
#define BSP_GPIO_BIT_MASK_TPB7     BSP_GPIO_BIT_MASK_PB7


/**
 * PC0 - JTAG-TCK
 * PC1 - JTAG-TMS
 * PC2 - JTAG-TDI
 * PC3 - JTAG-TDO
 * PC4 - TPC4 (J27:24)
 * PC5 - TPC5 (J27:22)
 * PC6 - TPC6 (J27:20)
 * PC7 - TPC7 (J27:18)
 */
#define BSP_GPIO_PORT_ID_JTAG_TCK     BSP_GPIO_PORT_ID_PC0
#define BSP_GPIO_BASE_ADDR_JTAG_TCK   BSP_GPIO_BASE_ADDR_PC0
#define BSP_GPIO_BIT_OFFSET_JTAG_TCK  BSP_GPIO_BIT_OFFSET_PC0
#define BSP_GPIO_BIT_MASK_JTAG_TCK    BSP_GPIO_BIT_MASK_PC0

#define BSP_GPIO_PORT_ID_JTAG_TMS     BSP_GPIO_PORT_ID_PC1
#define BSP_GPIO_BASE_ADDR_JTAG_TMS   BSP_GPIO_BASE_ADDR_PC1
#define BSP_GPIO_BIT_OFFSET_JTAG_TMS  BSP_GPIO_BIT_OFFSET_PC1
#define BSP_GPIO_BIT_MASK_JTAG_TMS    BSP_GPIO_BIT_MASK_PC1

#define BSP_GPIO_PORT_ID_JTAG_TDI     BSP_GPIO_PORT_ID_PC2
#define BSP_GPIO_BASE_ADDR_JTAG_TDI   BSP_GPIO_BASE_ADDR_PC2
#define BSP_GPIO_BIT_OFFSET_JTAG_TDI  BSP_GPIO_BIT_OFFSET_PC2
#define BSP_GPIO_BIT_MASK_JTAG_TDI    BSP_GPIO_BIT_MASK_PC2

#define BSP_GPIO_PORT_ID_JTAG_TDO     BSP_GPIO_PORT_ID_PC3
#define BSP_GPIO_BASE_ADDR_JTAG_TDO   BSP_GPIO_BASE_ADDR_PC3
#define BSP_GPIO_BIT_OFFSET_JTAG_TDO  BSP_GPIO_BIT_OFFSET_PC3
#define BSP_GPIO_BIT_MASK_JTAG_TDO    BSP_GPIO_BIT_MASK_PC3

#define BSP_GPIO_PORT_ID_TPC4         BSP_GPIO_PORT_ID_PC4
#define BSP_GPIO_BASE_ADDR_TPC4       BSP_GPIO_BASE_ADDR_PC4
#define BSP_GPIO_BIT_OFFSET_TPC4      BSP_GPIO_BIT_OFFSET_PC4
#define BSP_GPIO_BIT_MASK_TPC4        BSP_GPIO_BIT_MASK_PC4

#define BSP_GPIO_PORT_ID_TPC5         BSP_GPIO_PORT_ID_PC5
#define BSP_GPIO_BASE_ADDR_TPC5       BSP_GPIO_BASE_ADDR_PC5
#define BSP_GPIO_BIT_OFFSET_TPC5      BSP_GPIO_BIT_OFFSET_PC5
#define BSP_GPIO_BIT_MASK_TPC5        BSP_GPIO_BIT_MASK_PC5

#define BSP_GPIO_PORT_ID_TPC6         BSP_GPIO_PORT_ID_PC6
#define BSP_GPIO_BASE_ADDR_TPC6       BSP_GPIO_BASE_ADDR_PC6
#define BSP_GPIO_BIT_OFFSET_TPC6      BSP_GPIO_BIT_OFFSET_PC6
#define BSP_GPIO_BIT_MASK_TPC6        BSP_GPIO_BIT_MASK_PC6

#define BSP_GPIO_PORT_ID_TPC7         BSP_GPIO_PORT_ID_PC7
#define BSP_GPIO_BASE_ADDR_TPC7       BSP_GPIO_BASE_ADDR_PC7
#define BSP_GPIO_BIT_OFFSET_TPC7      BSP_GPIO_BIT_OFFSET_PC7
#define BSP_GPIO_BIT_MASK_TPC7        BSP_GPIO_BIT_MASK_PC7


/**
 * PD0 - TPD0 (J6:2)
 * PD1 - TPD1 (J9:2)
 * PD2 - TPD2 (J19:10)
 * PD3 - TPD3 (J30:D2)
 * PD4 - TPD4 (J21) Speaker Amp Enable
 * PD5 - TPD5 (J9:10)
 * PD6 - USB_PEN
 * PD7 - USB_PLFT
 */
#define BSP_GPIO_PORT_ID_TPD0        BSP_GPIO_PORT_ID_PD0
#define BSP_GPIO_BASE_ADDR_TPD0      BSP_GPIO_BASE_ADDR_PD0
#define BSP_GPIO_BIT_OFFSET_TPD0     BSP_GPIO_BIT_OFFSET_PD0
#define BSP_GPIO_BIT_MASK_TPD0       BSP_GPIO_BIT_MASK_PD0

#define BSP_GPIO_PORT_ID_TPD1        BSP_GPIO_PORT_ID_PD1
#define BSP_GPIO_BASE_ADDR_TPD1      BSP_GPIO_BASE_ADDR_PD1
#define BSP_GPIO_BIT_OFFSET_TPD1     BSP_GPIO_BIT_OFFSET_PD1
#define BSP_GPIO_BIT_MASK_TPD1       BSP_GPIO_BIT_MASK_PD1

#define BSP_GPIO_PORT_ID_TPD2        BSP_GPIO_PORT_ID_PD2
#define BSP_GPIO_BASE_ADDR_TPD2      BSP_GPIO_BASE_ADDR_PD2
#define BSP_GPIO_BIT_OFFSET_TPD2     BSP_GPIO_BIT_OFFSET_PD2
#define BSP_GPIO_BIT_MASK_TPD2       BSP_GPIO_BIT_MASK_PD2

#define BSP_GPIO_PORT_ID_TPD3        BSP_GPIO_PORT_ID_PD3
#define BSP_GPIO_BASE_ADDR_TPD3      BSP_GPIO_BASE_ADDR_PD3
#define BSP_GPIO_BIT_OFFSET_TPD3     BSP_GPIO_BIT_OFFSET_PD3
#define BSP_GPIO_BIT_MASK_TPD3       BSP_GPIO_BIT_MASK_PD3

#define BSP_GPIO_PORT_ID_TPD4        BSP_GPIO_PORT_ID_PD4
#define BSP_GPIO_BASE_ADDR_TPD4      BSP_GPIO_BASE_ADDR_PD4
#define BSP_GPIO_BIT_OFFSET_TPD4     BSP_GPIO_BIT_OFFSET_PD4
#define BSP_GPIO_BIT_MASK_TPD4       BSP_GPIO_BIT_MASK_PD4

#define BSP_GPIO_PORT_ID_TPD5        BSP_GPIO_PORT_ID_PD5
#define BSP_GPIO_BASE_ADDR_TPD5      BSP_GPIO_BASE_ADDR_PD5
#define BSP_GPIO_BIT_OFFSET_TPD5     BSP_GPIO_BIT_OFFSET_PD5
#define BSP_GPIO_BIT_MASK_TPD5       BSP_GPIO_BIT_MASK_PD5

#define BSP_GPIO_PORT_ID_USB_PEN     BSP_GPIO_PORT_ID_PD6
#define BSP_GPIO_BASE_ADDR_USB_PEN   BSP_GPIO_BASE_ADDR_PD6
#define BSP_GPIO_BIT_OFFSET_USB_PEN  BSP_GPIO_BIT_OFFSET_PD6
#define BSP_GPIO_BIT_MASK_USB_PEN    BSP_GPIO_BIT_MASK_PD6

#define BSP_GPIO_PORT_ID_USB_PLFT    BSP_GPIO_PORT_ID_PD7
#define BSP_GPIO_BASE_ADDR_USB_PLFT  BSP_GPIO_BASE_ADDR_PD7
#define BSP_GPIO_BIT_OFFSET_USB_PLFT BSP_GPIO_BIT_OFFSET_PD7
#define BSP_GPIO_BIT_MASK_USB_PLFT   BSP_GPIO_BIT_MASK_PD7


/**
 * PE0 - TPE0 (J29:C9)
 * PE1 - TPE1 (J29:C10)
 * PE2 - TPE2
 * PE3 - TPE3 (J29:C3)
 * PE4 - TPE4 (J29:A2)
 * PE5 - USR_SW3
 * PE6 - TPE6 (J29:C4)
 * PE7 - TPE7 (J34:5) TOUCH_AN0
 */
#define BSP_GPIO_PORT_ID_TPE0    BSP_GPIO_PORT_ID_PE0
#define BSP_GPIO_BASE_ADDR_TPE0  BSP_GPIO_BASE_ADDR_PE0
#define BSP_GPIO_BIT_OFFSET_TPE0 BSP_GPIO_BIT_OFFSET_PE0
#define BSP_GPIO_BIT_MASK_TPE0   BSP_GPIO_BIT_MASK_PE0

#define BSP_GPIO_PORT_ID_TPE1    BSP_GPIO_PORT_ID_PE1
#define BSP_GPIO_BASE_ADDR_TPE1  BSP_GPIO_BASE_ADDR_PE1
#define BSP_GPIO_BIT_OFFSET_TPE1 BSP_GPIO_BIT_OFFSET_PE1
#define BSP_GPIO_BIT_MASK_TPE1   BSP_GPIO_BIT_MASK_PE1

#define BSP_GPIO_PORT_ID_TPE2    BSP_GPIO_PORT_ID_PE2
#define BSP_GPIO_BASE_ADDR_TPE2  BSP_GPIO_BASE_ADDR_PE2
#define BSP_GPIO_BIT_OFFSET_TPE2 BSP_GPIO_BIT_OFFSET_PE2
#define BSP_GPIO_BIT_MASK_TPE2   BSP_GPIO_BIT_MASK_PE2

#define BSP_GPIO_PORT_ID_TPE3    BSP_GPIO_PORT_ID_PE3
#define BSP_GPIO_BASE_ADDR_TPE3  BSP_GPIO_BASE_ADDR_PE3
#define BSP_GPIO_BIT_OFFSET_TPE3 BSP_GPIO_BIT_OFFSET_PE3
#define BSP_GPIO_BIT_MASK_TPE3   BSP_GPIO_BIT_MASK_PE3

#define BSP_GPIO_PORT_ID_TPE4    BSP_GPIO_PORT_ID_PE4
#define BSP_GPIO_BASE_ADDR_TPE4  BSP_GPIO_BASE_ADDR_PE4
#define BSP_GPIO_BIT_OFFSET_TPE4 BSP_GPIO_BIT_OFFSET_PE4
#define BSP_GPIO_BIT_MASK_TPE4   BSP_GPIO_BIT_MASK_PE4

#define BSP_GPIO_PORT_ID_USR_SW3     BSP_GPIO_PORT_ID_PE5
#define BSP_GPIO_BASE_ADDR_USR_SW3   BSP_GPIO_BASE_ADDR_PE5
#define BSP_GPIO_BIT_OFFSET_USR_SW3  BSP_GPIO_BIT_OFFSET_PE5
#define BSP_GPIO_BIT_MASK_USR_SW3    BSP_GPIO_BIT_MASK_PE5

#define BSP_GPIO_PORT_ID_TPE6    BSP_GPIO_PORT_ID_PE5
#define BSP_GPIO_BASE_ADDR_TPE6  BSP_GPIO_BASE_ADDR_PE5
#define BSP_GPIO_BIT_OFFSET_TPE6 BSP_GPIO_BIT_OFFSET_PE5
#define BSP_GPIO_BIT_MASK_TPE6   BSP_GPIO_BIT_MASK_PE5

#define BSP_GPIO_PORT_ID_TPE7    BSP_GPIO_PORT_ID_PE5
#define BSP_GPIO_BASE_ADDR_TPE7  BSP_GPIO_BASE_ADDR_PE5
#define BSP_GPIO_BIT_OFFSET_TPE7 BSP_GPIO_BIT_OFFSET_PE5
#define BSP_GPIO_BIT_MASK_TPE7   BSP_GPIO_BIT_MASK_PE5


/**
 * PF0 - TPF0 (J7:7) FLASH_DAT1
 * PF1 - LED2 (J33:5)
 * PF2 - TPF2 (J28:5)
 * PF3 - TPF3 (J28:4)
 * PF4 - TPF4 (J7:9) FLASH_DAT2
 * PF5 - TPF5 (J7:11) FLASH_DAT3
 * PF6 - TPF6 (J34:13) LCD_CLK
 * PF7 - TPF7 (J34:21) LCD_DAT2
 */
#define BSP_GPIO_PORT_ID_TPF0      BSP_GPIO_PORT_ID_PF0
#define BSP_GPIO_BASE_ADDR_TPF0    BSP_GPIO_BASE_ADDR_PF0
#define BSP_GPIO_BIT_OFFSET_TPF0   BSP_GPIO_BIT_OFFSET_PF0
#define BSP_GPIO_BIT_MASK_TPF0     BSP_GPIO_BIT_MASK_PF0

#define BSP_GPIO_PORT_ID_LED2      BSP_GPIO_PORT_ID_PF1
#define BSP_GPIO_BASE_ADDR_LED2    BSP_GPIO_BASE_ADDR_PF1
#define BSP_GPIO_BIT_OFFSET_LED2   BSP_GPIO_BIT_OFFSET_PF1
#define BSP_GPIO_BIT_MASK_LED2     BSP_GPIO_BIT_MASK_PF1

#define BSP_GPIO_PORT_ID_TPF2      BSP_GPIO_PORT_ID_PF2
#define BSP_GPIO_BASE_ADDR_TPF2    BSP_GPIO_BASE_ADDR_PF2
#define BSP_GPIO_BIT_OFFSET_TPF2   BSP_GPIO_BIT_OFFSET_PF2
#define BSP_GPIO_BIT_MASK_TPF2     BSP_GPIO_BIT_MASK_PF2

#define BSP_GPIO_PORT_ID_TPF3      BSP_GPIO_PORT_ID_PF3
#define BSP_GPIO_BASE_ADDR_TPF3    BSP_GPIO_BASE_ADDR_PF3
#define BSP_GPIO_BIT_OFFSET_TPF3   BSP_GPIO_BIT_OFFSET_PF3
#define BSP_GPIO_BIT_MASK_TPF3     BSP_GPIO_BIT_MASK_PF3

#define BSP_GPIO_PORT_ID_TPF4      BSP_GPIO_PORT_ID_PF4
#define BSP_GPIO_BASE_ADDR_TPF4    BSP_GPIO_BASE_ADDR_PF4
#define BSP_GPIO_BIT_OFFSET_TPF4   BSP_GPIO_BIT_OFFSET_PF4
#define BSP_GPIO_BIT_MASK_TPF4     BSP_GPIO_BIT_MASK_PF4

#define BSP_GPIO_PORT_ID_TPF5      BSP_GPIO_PORT_ID_PF5
#define BSP_GPIO_BASE_ADDR_TPF5    BSP_GPIO_BASE_ADDR_PF5
#define BSP_GPIO_BIT_OFFSET_TPF5   BSP_GPIO_BIT_OFFSET_PF5
#define BSP_GPIO_BIT_MASK_TPF5     BSP_GPIO_BIT_MASK_PF5

#define BSP_GPIO_PORT_ID_TPF6      BSP_GPIO_PORT_ID_PF6
#define BSP_GPIO_BASE_ADDR_TPF6    BSP_GPIO_BASE_ADDR_PF6
#define BSP_GPIO_BIT_OFFSET_TPF6   BSP_GPIO_BIT_OFFSET_PF6
#define BSP_GPIO_BIT_MASK_TPF6     BSP_GPIO_BIT_MASK_PF6

#define BSP_GPIO_PORT_ID_TPF7      BSP_GPIO_PORT_ID_PF7
#define BSP_GPIO_BASE_ADDR_TPF7    BSP_GPIO_BASE_ADDR_PF7
#define BSP_GPIO_BIT_OFFSET_TPF7   BSP_GPIO_BIT_OFFSET_PF7
#define BSP_GPIO_BIT_MASK_TPF7     BSP_GPIO_BIT_MASK_PF7


/**
 * PG0 - TPG0 (J27:31)
 * PG1 - TPG1 (J27:29)
 * PG2 - TPG2 (J28:7)
 * PG3 - TPG3 (J28:16)
 * PG4 - TPG4 (J28:23)
 * PG5 - TPG5 (J28:25)
 * PG6 - TPG6 (J28:18)
 * PG7 - TPG7 (J28:6)
 */
#define BSP_GPIO_PORT_ID_TPG0      BSP_GPIO_PORT_ID_PG0
#define BSP_GPIO_BASE_ADDR_TPG0    BSP_GPIO_BASE_ADDR_PG0
#define BSP_GPIO_BIT_OFFSET_TPG0   BSP_GPIO_BIT_OFFSET_PG0
#define BSP_GPIO_BIT_MASK_TPG0     BSP_GPIO_BIT_MASK_PG0

#define BSP_GPIO_PORT_ID_TPG1      BSP_GPIO_PORT_ID_PG1
#define BSP_GPIO_BASE_ADDR_TPG1    BSP_GPIO_BASE_ADDR_PG1
#define BSP_GPIO_BIT_OFFSET_TPG1   BSP_GPIO_BIT_OFFSET_PG1
#define BSP_GPIO_BIT_MASK_TPG1     BSP_GPIO_BIT_MASK_PG1

#define BSP_GPIO_PORT_ID_TPG2      BSP_GPIO_PORT_ID_PG2
#define BSP_GPIO_BASE_ADDR_TPG2    BSP_GPIO_BASE_ADDR_PG2
#define BSP_GPIO_BIT_OFFSET_TPG2   BSP_GPIO_BIT_OFFSET_PG2
#define BSP_GPIO_BIT_MASK_TPG2     BSP_GPIO_BIT_MASK_PG2

#define BSP_GPIO_PORT_ID_TPG3      BSP_GPIO_PORT_ID_PG3
#define BSP_GPIO_BASE_ADDR_TPG3    BSP_GPIO_BASE_ADDR_PG3
#define BSP_GPIO_BIT_OFFSET_TPG3   BSP_GPIO_BIT_OFFSET_PG3
#define BSP_GPIO_BIT_MASK_TPG3     BSP_GPIO_BIT_MASK_PG3

#define BSP_GPIO_PORT_ID_TPG4      BSP_GPIO_PORT_ID_PG4
#define BSP_GPIO_BASE_ADDR_TPG4    BSP_GPIO_BASE_ADDR_PG4
#define BSP_GPIO_BIT_OFFSET_TPG4   BSP_GPIO_BIT_OFFSET_PG4
#define BSP_GPIO_BIT_MASK_TPG4     BSP_GPIO_BIT_MASK_PG4

#define BSP_GPIO_PORT_ID_TPG5      BSP_GPIO_PORT_ID_PG5
#define BSP_GPIO_BASE_ADDR_TPG5    BSP_GPIO_BASE_ADDR_PG5
#define BSP_GPIO_BIT_OFFSET_TPG5   BSP_GPIO_BIT_OFFSET_PG5
#define BSP_GPIO_BIT_MASK_TPG5     BSP_GPIO_BIT_MASK_PG5

#define BSP_GPIO_PORT_ID_TPG6      BSP_GPIO_PORT_ID_PG6
#define BSP_GPIO_BASE_ADDR_TPG6    BSP_GPIO_BASE_ADDR_PG6
#define BSP_GPIO_BIT_OFFSET_TPG6   BSP_GPIO_BIT_OFFSET_PG6
#define BSP_GPIO_BIT_MASK_TPG6     BSP_GPIO_BIT_MASK_PG6

#define BSP_GPIO_PORT_ID_TPG7      BSP_GPIO_PORT_ID_PG7
#define BSP_GPIO_BASE_ADDR_TPG7    BSP_GPIO_BASE_ADDR_PG7
#define BSP_GPIO_BIT_OFFSET_TPG7   BSP_GPIO_BIT_OFFSET_PG7
#define BSP_GPIO_BIT_MASK_TPG7     BSP_GPIO_BIT_MASK_PG7


/**
 * PH0 - TPH0 (J28:20)
 * PH1 - TPH1 (J28:22)
 * PH2 - TPH2 (J28:24)
 * PH3 - TPH3 (J28:26)
 * PH4 - TPH4 (J7:13) SD_CS
 * PH5 - TPH5 (J9:8)
 * PH6 - TPH6 (J29:A3)
 * PH7 - TPH7 (J29:A4)
 */
#define BSP_GPIO_PORT_ID_TPH0      BSP_GPIO_PORT_ID_PH0
#define BSP_GPIO_BASE_ADDR_TPH0    BSP_GPIO_BASE_ADDR_PH0
#define BSP_GPIO_BIT_OFFSET_TPH0   BSP_GPIO_BIT_OFFSET_PH0
#define BSP_GPIO_BIT_MASK_TPH0     BSP_GPIO_BIT_MASK_PH0

#define BSP_GPIO_PORT_ID_TPH1      BSP_GPIO_PORT_ID_PH1
#define BSP_GPIO_BASE_ADDR_TPH1    BSP_GPIO_BASE_ADDR_PH1
#define BSP_GPIO_BIT_OFFSET_TPH1   BSP_GPIO_BIT_OFFSET_PH1
#define BSP_GPIO_BIT_MASK_TPH1     BSP_GPIO_BIT_MASK_PH1

#define BSP_GPIO_PORT_ID_TPH2      BSP_GPIO_PORT_ID_PH2
#define BSP_GPIO_BASE_ADDR_TPH2    BSP_GPIO_BASE_ADDR_PH2
#define BSP_GPIO_BIT_OFFSET_TPH2   BSP_GPIO_BIT_OFFSET_PH2
#define BSP_GPIO_BIT_MASK_TPH2     BSP_GPIO_BIT_MASK_PH2

#define BSP_GPIO_PORT_ID_TPH3      BSP_GPIO_PORT_ID_PH3
#define BSP_GPIO_BASE_ADDR_TPH3    BSP_GPIO_BASE_ADDR_PH3
#define BSP_GPIO_BIT_OFFSET_TPH3   BSP_GPIO_BIT_OFFSET_PH3
#define BSP_GPIO_BIT_MASK_TPH3     BSP_GPIO_BIT_MASK_PH3

#define BSP_GPIO_PORT_ID_TPH4      BSP_GPIO_PORT_ID_PH4
#define BSP_GPIO_BASE_ADDR_TPH4    BSP_GPIO_BASE_ADDR_PH4
#define BSP_GPIO_BIT_OFFSET_TPH4   BSP_GPIO_BIT_OFFSET_PH4
#define BSP_GPIO_BIT_MASK_TPH4     BSP_GPIO_BIT_MASK_PH4

#define BSP_GPIO_PORT_ID_TPH5      BSP_GPIO_PORT_ID_PH5
#define BSP_GPIO_BASE_ADDR_TPH5    BSP_GPIO_BASE_ADDR_PH5
#define BSP_GPIO_BIT_OFFSET_TPH5   BSP_GPIO_BIT_OFFSET_PH5
#define BSP_GPIO_BIT_MASK_TPH5     BSP_GPIO_BIT_MASK_PH5

#define BSP_GPIO_PORT_ID_TPH6      BSP_GPIO_PORT_ID_PH6
#define BSP_GPIO_BASE_ADDR_TPH6    BSP_GPIO_BASE_ADDR_PH6
#define BSP_GPIO_BIT_OFFSET_TPH6   BSP_GPIO_BIT_OFFSET_PH6
#define BSP_GPIO_BIT_MASK_TPH6     BSP_GPIO_BIT_MASK_PH6

#define BSP_GPIO_PORT_ID_TPH7      BSP_GPIO_PORT_ID_PH7
#define BSP_GPIO_BASE_ADDR_TPH7    BSP_GPIO_BASE_ADDR_PH7
#define BSP_GPIO_BIT_OFFSET_TPH7   BSP_GPIO_BIT_OFFSET_PH7
#define BSP_GPIO_BIT_MASK_TPH7     BSP_GPIO_BIT_MASK_PH7


/**
 * PJ0 - TPJ0 (J12:2)
 * PJ1 - TPJ1 (J13:2)
 * PJ2 - TPJ2 (J29:A8)
 * PJ3 - TPJ3 (J9:3)
 * PJ4 - TPJ4 (J19:3)
 * PJ5 - TPJ5 (J31:18)
 * PJ6 - TPJ6 (J34:15) LCDAC
 * PJ7 - TPJ7 (J29:A10)
 */
#define BSP_GPIO_PORT_ID_TPJ0      BSP_GPIO_PORT_ID_PJ0
#define BSP_GPIO_BASE_ADDR_TPJ0    BSP_GPIO_BASE_ADDR_PJ0
#define BSP_GPIO_BIT_OFFSET_TPJ0   BSP_GPIO_BIT_OFFSET_PJ0
#define BSP_GPIO_BIT_MASK_TPJ0     BSP_GPIO_BIT_MASK_PJ0

#define BSP_GPIO_PORT_ID_TPJ1      BSP_GPIO_PORT_ID_PJ1
#define BSP_GPIO_BASE_ADDR_TPJ1    BSP_GPIO_BASE_ADDR_PJ1
#define BSP_GPIO_BIT_OFFSET_TPJ1   BSP_GPIO_BIT_OFFSET_PJ1
#define BSP_GPIO_BIT_MASK_TPJ1     BSP_GPIO_BIT_MASK_PJ1

#define BSP_GPIO_PORT_ID_TPJ2      BSP_GPIO_PORT_ID_PJ2
#define BSP_GPIO_BASE_ADDR_TPJ2    BSP_GPIO_BASE_ADDR_PJ2
#define BSP_GPIO_BIT_OFFSET_TPJ2   BSP_GPIO_BIT_OFFSET_PJ2
#define BSP_GPIO_BIT_MASK_TPJ2     BSP_GPIO_BIT_MASK_PJ2

#define BSP_GPIO_PORT_ID_TPJ3      BSP_GPIO_PORT_ID_PJ3
#define BSP_GPIO_BASE_ADDR_TPJ3    BSP_GPIO_BASE_ADDR_PJ3
#define BSP_GPIO_BIT_OFFSET_TPJ3   BSP_GPIO_BIT_OFFSET_PJ3
#define BSP_GPIO_BIT_MASK_TPJ3     BSP_GPIO_BIT_MASK_PJ3

#define BSP_GPIO_PORT_ID_TPJ4      BSP_GPIO_PORT_ID_PJ4
#define BSP_GPIO_BASE_ADDR_TPJ4    BSP_GPIO_BASE_ADDR_PJ4
#define BSP_GPIO_BIT_OFFSET_TPJ4   BSP_GPIO_BIT_OFFSET_PJ4
#define BSP_GPIO_BIT_MASK_TPJ4     BSP_GPIO_BIT_MASK_PJ4

#define BSP_GPIO_PORT_ID_TPJ5      BSP_GPIO_PORT_ID_PJ5
#define BSP_GPIO_BASE_ADDR_TPJ5    BSP_GPIO_BASE_ADDR_PJ5
#define BSP_GPIO_BIT_OFFSET_TPJ5   BSP_GPIO_BIT_OFFSET_PJ5
#define BSP_GPIO_BIT_MASK_TPJ5     BSP_GPIO_BIT_MASK_PJ5

#define BSP_GPIO_PORT_ID_TPJ6      BSP_GPIO_PORT_ID_PJ6
#define BSP_GPIO_BASE_ADDR_TPJ6    BSP_GPIO_BASE_ADDR_PJ6
#define BSP_GPIO_BIT_OFFSET_TPJ6   BSP_GPIO_BIT_OFFSET_PJ6
#define BSP_GPIO_BIT_MASK_TPJ6     BSP_GPIO_BIT_MASK_PJ6

#define BSP_GPIO_PORT_ID_TPJ7      BSP_GPIO_PORT_ID_PJ7
#define BSP_GPIO_BASE_ADDR_TPJ7    BSP_GPIO_BASE_ADDR_PJ7
#define BSP_GPIO_BIT_OFFSET_TPJ7   BSP_GPIO_BIT_OFFSET_PJ7
#define BSP_GPIO_BIT_MASK_TPJ7     BSP_GPIO_BIT_MASK_PJ7


/**
 * PK0 - TPK0 (J29:C5)
 * PK1 - TPK1 (J29:C6)
 * PK2 - TPK2 (J29:C7)
 * PK3 - TPK3 (J29:C8)
 * PK4 - LED0 (J33:1)
 * PK5 - TPK5 (J28:19)
 * PK6 - LED1 (J33:3)
 * PK7 - TPK7 (J28:29)
 */
#define BSP_GPIO_PORT_ID_TPK0      BSP_GPIO_PORT_ID_PK0
#define BSP_GPIO_BASE_ADDR_TPK0    BSP_GPIO_BASE_ADDR_PK0
#define BSP_GPIO_BIT_OFFSET_TPK0   BSP_GPIO_BIT_OFFSET_PK0
#define BSP_GPIO_BIT_MASK_TPK0     BSP_GPIO_BIT_MASK_PK0

#define BSP_GPIO_PORT_ID_TPK1      BSP_GPIO_PORT_ID_PK1
#define BSP_GPIO_BASE_ADDR_TPK1    BSP_GPIO_BASE_ADDR_PK1
#define BSP_GPIO_BIT_OFFSET_TPK1   BSP_GPIO_BIT_OFFSET_PK1
#define BSP_GPIO_BIT_MASK_TPK1     BSP_GPIO_BIT_MASK_PK1

#define BSP_GPIO_PORT_ID_TPK2      BSP_GPIO_PORT_ID_PK2
#define BSP_GPIO_BASE_ADDR_TPK2    BSP_GPIO_BASE_ADDR_PK2
#define BSP_GPIO_BIT_OFFSET_TPK2   BSP_GPIO_BIT_OFFSET_PK2
#define BSP_GPIO_BIT_MASK_TPK2     BSP_GPIO_BIT_MASK_PK2

#define BSP_GPIO_PORT_ID_TPK3      BSP_GPIO_PORT_ID_PK3
#define BSP_GPIO_BASE_ADDR_TPK3    BSP_GPIO_BASE_ADDR_PK3
#define BSP_GPIO_BIT_OFFSET_TPK3   BSP_GPIO_BIT_OFFSET_PK3
#define BSP_GPIO_BIT_MASK_TPK3     BSP_GPIO_BIT_MASK_PK3

#define BSP_GPIO_PORT_ID_LED0      BSP_GPIO_PORT_ID_PK4
#define BSP_GPIO_BASE_ADDR_LED0    BSP_GPIO_BASE_ADDR_PK4
#define BSP_GPIO_BIT_OFFSET_LED0   BSP_GPIO_BIT_OFFSET_PK4
#define BSP_GPIO_BIT_MASK_LED0     BSP_GPIO_BIT_MASK_PK4

#define BSP_GPIO_PORT_ID_TPK5      BSP_GPIO_PORT_ID_PK6
#define BSP_GPIO_BASE_ADDR_TPK5    BSP_GPIO_BASE_ADDR_PK6
#define BSP_GPIO_BIT_OFFSET_TPK5   BSP_GPIO_BIT_OFFSET_PK6
#define BSP_GPIO_BIT_MASK_TPK5     BSP_GPIO_BIT_MASK_PK6

#define BSP_GPIO_PORT_ID_LED1      BSP_GPIO_PORT_ID_PK6
#define BSP_GPIO_BASE_ADDR_LED1    BSP_GPIO_BASE_ADDR_PK6
#define BSP_GPIO_BIT_OFFSET_LED1   BSP_GPIO_BIT_OFFSET_PK6
#define BSP_GPIO_BIT_MASK_LED1     BSP_GPIO_BIT_MASK_PK6

#define BSP_GPIO_PORT_ID_TPK7      BSP_GPIO_PORT_ID_PK7
#define BSP_GPIO_BASE_ADDR_TPK7    BSP_GPIO_BASE_ADDR_PK7
#define BSP_GPIO_BIT_OFFSET_TPK7   BSP_GPIO_BIT_OFFSET_PK7
#define BSP_GPIO_BIT_MASK_TPK7     BSP_GPIO_BIT_MASK_PK7


/**
 * PL0 - TPL0 (J27:9)
 * PL1 - TPL1 (J27:7)
 * PL2 - TPL2 (J27:11)
 * PL3 - TPL3 (J27:13)
 * PL4 - TPL4 (J27:15)
 * PL5 - TPL5 (J27:17)
 * PL6 - USB_DP
 * PL7 - USB_DM
 */
#define BSP_GPIO_PORT_ID_TPL0      BSP_GPIO_PORT_ID_PL0
#define BSP_GPIO_BASE_ADDR_TPL0    BSP_GPIO_BASE_ADDR_PL0
#define BSP_GPIO_BIT_OFFSET_TPL0   BSP_GPIO_BIT_OFFSET_PL0
#define BSP_GPIO_BIT_MASK_TPL0     BSP_GPIO_BIT_MASK_PL0

#define BSP_GPIO_PORT_ID_TPL1      BSP_GPIO_PORT_ID_PL1
#define BSP_GPIO_BASE_ADDR_TPL1    BSP_GPIO_BASE_ADDR_PL1
#define BSP_GPIO_BIT_OFFSET_TPL1   BSP_GPIO_BIT_OFFSET_PL1
#define BSP_GPIO_BIT_MASK_TPL1     BSP_GPIO_BIT_MASK_PL1

#define BSP_GPIO_PORT_ID_TPL2      BSP_GPIO_PORT_ID_PL2
#define BSP_GPIO_BASE_ADDR_TPL2    BSP_GPIO_BASE_ADDR_PL2
#define BSP_GPIO_BIT_OFFSET_TPL2   BSP_GPIO_BIT_OFFSET_PL2
#define BSP_GPIO_BIT_MASK_TPL2     BSP_GPIO_BIT_MASK_PL2

#define BSP_GPIO_PORT_ID_TPL3      BSP_GPIO_PORT_ID_PL3
#define BSP_GPIO_BASE_ADDR_TPL3    BSP_GPIO_BASE_ADDR_PL3
#define BSP_GPIO_BIT_OFFSET_TPL3   BSP_GPIO_BIT_OFFSET_PL3
#define BSP_GPIO_BIT_MASK_TPL3     BSP_GPIO_BIT_MASK_PL3

#define BSP_GPIO_PORT_ID_TPL4      BSP_GPIO_PORT_ID_PL4
#define BSP_GPIO_BASE_ADDR_TPL4    BSP_GPIO_BASE_ADDR_PL4
#define BSP_GPIO_BIT_OFFSET_TPL4   BSP_GPIO_BIT_OFFSET_PL4
#define BSP_GPIO_BIT_MASK_TPL4     BSP_GPIO_BIT_MASK_PL4

#define BSP_GPIO_PORT_ID_TPL5      BSP_GPIO_PORT_ID_PL6
#define BSP_GPIO_BASE_ADDR_TPL5    BSP_GPIO_BASE_ADDR_PL6
#define BSP_GPIO_BIT_OFFSET_TPL5   BSP_GPIO_BIT_OFFSET_PL6
#define BSP_GPIO_BIT_MASK_TPL5     BSP_GPIO_BIT_MASK_PL6

#define BSP_GPIO_PORT_ID_USB_DP    BSP_GPIO_PORT_ID_PL6
#define BSP_GPIO_BASE_ADDR_USB_DP  BSP_GPIO_BASE_ADDR_PL6
#define BSP_GPIO_BIT_OFFSET_USB_DP BSP_GPIO_BIT_OFFSET_PL6
#define BSP_GPIO_BIT_MASK_USB_DP   BSP_GPIO_BIT_MASK_PL6

#define BSP_GPIO_PORT_ID_USB_DM    BSP_GPIO_PORT_ID_PL7
#define BSP_GPIO_BASE_ADDR_USB_DM  BSP_GPIO_BASE_ADDR_PL7
#define BSP_GPIO_BIT_OFFSET_USB_DM BSP_GPIO_BIT_OFFSET_PL7
#define BSP_GPIO_BIT_MASK_USB_DM   BSP_GPIO_BIT_MASK_PL7


/**
 * PM0 - TPM0 (J27:14)
 * PM1 - TPM1 (J27:12)
 * PM2 - TPM2 (J27:10)
 * PM3 - TPM3 (J27:8)
 * PM4 - TPM4 (J28:11)
 * PM5 - TPM5 (J30:D1)
 * PM6 - TPM6 (J28:3)
 * PM7 - TPM7 (J28:30)
 */
#define BSP_GPIO_PORT_ID_TPM0      BSP_GPIO_PORT_ID_PM0
#define BSP_GPIO_BASE_ADDR_TPM0    BSP_GPIO_BASE_ADDR_PM0
#define BSP_GPIO_BIT_OFFSET_TPM0   BSP_GPIO_BIT_OFFSET_PM0
#define BSP_GPIO_BIT_MASK_TPM0     BSP_GPIO_BIT_MASK_PM0

#define BSP_GPIO_PORT_ID_TPM1      BSP_GPIO_PORT_ID_PM1
#define BSP_GPIO_BASE_ADDR_TPM1    BSP_GPIO_BASE_ADDR_PM1
#define BSP_GPIO_BIT_OFFSET_TPM1   BSP_GPIO_BIT_OFFSET_PM1
#define BSP_GPIO_BIT_MASK_TPM1     BSP_GPIO_BIT_MASK_PM1

#define BSP_GPIO_PORT_ID_TPM2      BSP_GPIO_PORT_ID_PM2
#define BSP_GPIO_BASE_ADDR_TPM2    BSP_GPIO_BASE_ADDR_PM2
#define BSP_GPIO_BIT_OFFSET_TPM2   BSP_GPIO_BIT_OFFSET_PM2
#define BSP_GPIO_BIT_MASK_TPM2     BSP_GPIO_BIT_MASK_PM2

#define BSP_GPIO_PORT_ID_TPM3      BSP_GPIO_PORT_ID_PM3
#define BSP_GPIO_BASE_ADDR_TPM3    BSP_GPIO_BASE_ADDR_PM3
#define BSP_GPIO_BIT_OFFSET_TPM3   BSP_GPIO_BIT_OFFSET_PM3
#define BSP_GPIO_BIT_MASK_TPM3     BSP_GPIO_BIT_MASK_PM3

#define BSP_GPIO_PORT_ID_TPM4      BSP_GPIO_PORT_ID_PM4
#define BSP_GPIO_BASE_ADDR_TPM4    BSP_GPIO_BASE_ADDR_PM4
#define BSP_GPIO_BIT_OFFSET_TPM4   BSP_GPIO_BIT_OFFSET_PM4
#define BSP_GPIO_BIT_MASK_TPM4     BSP_GPIO_BIT_MASK_PM4

#define BSP_GPIO_PORT_ID_TPM5      BSP_GPIO_PORT_ID_PM5
#define BSP_GPIO_BASE_ADDR_TPM5    BSP_GPIO_BASE_ADDR_PM5
#define BSP_GPIO_BIT_OFFSET_TPM5   BSP_GPIO_BIT_OFFSET_PM5
#define BSP_GPIO_BIT_MASK_TPM5     BSP_GPIO_BIT_MASK_PM5

#define BSP_GPIO_PORT_ID_TPM6      BSP_GPIO_PORT_ID_PM6
#define BSP_GPIO_BASE_ADDR_TPM6    BSP_GPIO_BASE_ADDR_PM6
#define BSP_GPIO_BIT_OFFSET_TPM6   BSP_GPIO_BIT_OFFSET_PM6
#define BSP_GPIO_BIT_MASK_TPM6     BSP_GPIO_BIT_MASK_PM6

#define BSP_GPIO_PORT_ID_TPM7      BSP_GPIO_PORT_ID_PM7
#define BSP_GPIO_BASE_ADDR_TPM7    BSP_GPIO_BASE_ADDR_PM7
#define BSP_GPIO_BIT_OFFSET_TPM7   BSP_GPIO_BIT_OFFSET_PM7
#define BSP_GPIO_BIT_MASK_TPM7     BSP_GPIO_BIT_MASK_PM7


/**
 * PN0 - TPN0 (J30:B8)
 * PN1 - TPN1 (J30:B9)
 * PN2 - TPN2 (J30:B10)
 * PN3 - USR_SW2 (J37:1) UP
 * PN4 - TPN4 (J27:16)
 * PN5 - LED_R (J36:11)
 * PN6 - TPN6 (J28:12)
 * PN7 - TPN7 (J29:A5)
 */
#define BSP_GPIO_PORT_ID_TPN0      BSP_GPIO_PORT_ID_PN0
#define BSP_GPIO_BASE_ADDR_TPN0    BSP_GPIO_BASE_ADDR_PN0
#define BSP_GPIO_BIT_OFFSET_TPN0   BSP_GPIO_BIT_OFFSET_PN0
#define BSP_GPIO_BIT_MASK_TPN0     BSP_GPIO_BIT_MASK_PN0

#define BSP_GPIO_PORT_ID_TPN1      BSP_GPIO_PORT_ID_PN1
#define BSP_GPIO_BASE_ADDR_TPN1    BSP_GPIO_BASE_ADDR_PN1
#define BSP_GPIO_BIT_OFFSET_TPN1   BSP_GPIO_BIT_OFFSET_PN1
#define BSP_GPIO_BIT_MASK_TPN1     BSP_GPIO_BIT_MASK_PN1

#define BSP_GPIO_PORT_ID_TPN2      BSP_GPIO_PORT_ID_PN2
#define BSP_GPIO_BASE_ADDR_TPN2    BSP_GPIO_BASE_ADDR_PN2
#define BSP_GPIO_BIT_OFFSET_TPN2   BSP_GPIO_BIT_OFFSET_PN2
#define BSP_GPIO_BIT_MASK_TPN2     BSP_GPIO_BIT_MASK_PN2

#define BSP_GPIO_PORT_ID_USR_SW2      BSP_GPIO_PORT_ID_PN3
#define BSP_GPIO_BASE_ADDR_USR_SW2    BSP_GPIO_BASE_ADDR_PN3
#define BSP_GPIO_BIT_OFFSET_USR_SW2   BSP_GPIO_BIT_OFFSET_PN3
#define BSP_GPIO_BIT_MASK_USR_SW2     BSP_GPIO_BIT_MASK_PN3

#define BSP_GPIO_PORT_ID_TPN4      BSP_GPIO_PORT_ID_PN4
#define BSP_GPIO_BASE_ADDR_TPN4    BSP_GPIO_BASE_ADDR_PN4
#define BSP_GPIO_BIT_OFFSET_TPN4   BSP_GPIO_BIT_OFFSET_PN4
#define BSP_GPIO_BIT_MASK_TPN4     BSP_GPIO_BIT_MASK_PN4

#define BSP_GPIO_PORT_ID_LED_R     BSP_GPIO_PORT_ID_PN5
#define BSP_GPIO_BASE_ADDR_LED_R   BSP_GPIO_BASE_ADDR_PN5
#define BSP_GPIO_BIT_OFFSET_LED_R  BSP_GPIO_BIT_OFFSET_PN5
#define BSP_GPIO_BIT_MASK_LED_R    BSP_GPIO_BIT_MASK_PN5

#define BSP_GPIO_PORT_ID_TPN6      BSP_GPIO_PORT_ID_PN6
#define BSP_GPIO_BASE_ADDR_TPN6    BSP_GPIO_BASE_ADDR_PN6
#define BSP_GPIO_BIT_OFFSET_TPN6   BSP_GPIO_BIT_OFFSET_PN6
#define BSP_GPIO_BIT_MASK_TPN6     BSP_GPIO_BIT_MASK_PN6

#define BSP_GPIO_PORT_ID_TPN7      BSP_GPIO_PORT_ID_PN7
#define BSP_GPIO_BASE_ADDR_TPN7    BSP_GPIO_BASE_ADDR_PN7
#define BSP_GPIO_BIT_OFFSET_TPN7   BSP_GPIO_BIT_OFFSET_PN7
#define BSP_GPIO_BIT_MASK_TPN7     BSP_GPIO_BIT_MASK_PN7


/**
 * PP0 - TPP0 (J28:13)
 * PP1 - USR_SW4 (J37:1) SEL
 * PP2 - TPP2 (J27:23)
 * PP3 - TPP3 (J27:27)
 * PP4 - TPP4 (J27:21)
 * PP5 - TPP5 (J27:19)
 * PP6 - TPP6 (J9:9)
 * PP7 - TPP7 (J34:11) TOUCH_AN1
 */
#define BSP_GPIO_PORT_ID_TPP0      BSP_GPIO_PORT_ID_PP0
#define BSP_GPIO_BASE_ADDR_TPP0    BSP_GPIO_BASE_ADDR_PP0
#define BSP_GPIO_BIT_OFFSET_TPP0   BSP_GPIO_BIT_OFFSET_PP0
#define BSP_GPIO_BIT_MASK_TPP0     BSP_GPIO_BIT_MASK_PP0

#define BSP_GPIO_PORT_ID_USR_SW4       BSP_GPIO_PORT_ID_PP1
#define BSP_GPIO_BASE_ADDR_USR_SW4     BSP_GPIO_BASE_ADDR_PP1
#define BSP_GPIO_BIT_OFFSET_USR_SW4    BSP_GPIO_BIT_OFFSET_PP1
#define BSP_GPIO_BIT_MASK_USR_SW4      BSP_GPIO_BIT_MASK_PP1

#define BSP_GPIO_PORT_ID_TPP2      BSP_GPIO_PORT_ID_PP2
#define BSP_GPIO_BASE_ADDR_TPP2    BSP_GPIO_BASE_ADDR_PP2
#define BSP_GPIO_BIT_OFFSET_TPP2   BSP_GPIO_BIT_OFFSET_PP2
#define BSP_GPIO_BIT_MASK_TPP2     BSP_GPIO_BIT_MASK_PP2

#define BSP_GPIO_PORT_ID_TPP3     BSP_GPIO_PORT_ID_PP3
#define BSP_GPIO_BASE_ADDR_TPP3   BSP_GPIO_BASE_ADDR_PP3
#define BSP_GPIO_BIT_OFFSET_TPP3  BSP_GPIO_BIT_OFFSET_PP3
#define BSP_GPIO_BIT_MASK_TPP3    BSP_GPIO_BIT_MASK_PP3

#define BSP_GPIO_PORT_ID_TPP4      BSP_GPIO_PORT_ID_PP4
#define BSP_GPIO_BASE_ADDR_TPP4    BSP_GPIO_BASE_ADDR_PP4
#define BSP_GPIO_BIT_OFFSET_TPP4   BSP_GPIO_BIT_OFFSET_PP4
#define BSP_GPIO_BIT_MASK_TPP4     BSP_GPIO_BIT_MASK_PP4

#define BSP_GPIO_PORT_ID_TPP5      BSP_GPIO_PORT_ID_PP5
#define BSP_GPIO_BASE_ADDR_TPP5    BSP_GPIO_BASE_ADDR_PP5
#define BSP_GPIO_BIT_OFFSET_TPP5   BSP_GPIO_BIT_OFFSET_PP5
#define BSP_GPIO_BIT_MASK_TPP5     BSP_GPIO_BIT_MASK_PP5

#define BSP_GPIO_PORT_ID_TPP6      BSP_GPIO_PORT_ID_PP6
#define BSP_GPIO_BASE_ADDR_TPP6    BSP_GPIO_BASE_ADDR_PP6
#define BSP_GPIO_BIT_OFFSET_TPP6   BSP_GPIO_BIT_OFFSET_PP6
#define BSP_GPIO_BIT_MASK_TPP6     BSP_GPIO_BIT_MASK_PP6

#define BSP_GPIO_PORT_ID_TPP7      BSP_GPIO_PORT_ID_PP7
#define BSP_GPIO_BASE_ADDR_TPP7    BSP_GPIO_BASE_ADDR_PP7
#define BSP_GPIO_BIT_OFFSET_TPP7   BSP_GPIO_BIT_OFFSET_PP7
#define BSP_GPIO_BIT_MASK_TPP7     BSP_GPIO_BIT_MASK_PP7


/**
 * PQ0 - TPQ0 (J7:3) FLASH_CS
 * PQ1 - TPQ1 (J7:1) FLASH_CLK
 * PQ2 - TPQ2 (J7:5) FLASH_DAT0
 * PQ3 - TPQ3 (J30:D8)
 * PQ4 - LED_B (J36:3)
 * PQ5 - TPQ5 (J28:15)
 * PQ6 - TPQ6 (J28:17)
 * PQ7 - LED_G (J36:5)
 */
#define BSP_GPIO_PORT_ID_TPQ0      BSP_GPIO_PORT_ID_PQ0
#define BSP_GPIO_BASE_ADDR_TPQ0    BSP_GPIO_BASE_ADDR_PQ0
#define BSP_GPIO_BIT_OFFSET_TPQ0   BSP_GPIO_BIT_OFFSET_PQ0
#define BSP_GPIO_BIT_MASK_TPQ0     BSP_GPIO_BIT_MASK_PQ0

#define BSP_GPIO_PORT_ID_TPQ1      BSP_GPIO_PORT_ID_PQ1
#define BSP_GPIO_BASE_ADDR_TPQ1    BSP_GPIO_BASE_ADDR_PQ1
#define BSP_GPIO_BIT_OFFSET_TPQ1   BSP_GPIO_BIT_OFFSET_PQ1
#define BSP_GPIO_BIT_MASK_TPQ1     BSP_GPIO_BIT_MASK_PQ1

#define BSP_GPIO_PORT_ID_TPQ2      BSP_GPIO_PORT_ID_PQ2
#define BSP_GPIO_BASE_ADDR_TPQ2    BSP_GPIO_BASE_ADDR_PQ2
#define BSP_GPIO_BIT_OFFSET_TPQ2   BSP_GPIO_BIT_OFFSET_PQ2
#define BSP_GPIO_BIT_MASK_TPQ2     BSP_GPIO_BIT_MASK_PQ2

#define BSP_GPIO_PORT_ID_TPQ3     BSP_GPIO_PORT_ID_PQ3
#define BSP_GPIO_BASE_ADDR_TPQ3   BSP_GPIO_BASE_ADDR_PQ3
#define BSP_GPIO_BIT_OFFSET_TPQ3  BSP_GPIO_BIT_OFFSET_PQ3
#define BSP_GPIO_BIT_MASK_TPQ3    BSP_GPIO_BIT_MASK_PQ3

#define BSP_GPIO_PORT_ID_LED_B      BSP_GPIO_PORT_ID_PQ4
#define BSP_GPIO_BASE_ADDR_LED_B    BSP_GPIO_BASE_ADDR_PQ4
#define BSP_GPIO_BIT_OFFSET_LED_B   BSP_GPIO_BIT_OFFSET_PQ4
#define BSP_GPIO_BIT_MASK_LED_B     BSP_GPIO_BIT_MASK_PQ4

#define BSP_GPIO_PORT_ID_TPQ5      BSP_GPIO_PORT_ID_PQ5
#define BSP_GPIO_BASE_ADDR_TPQ5    BSP_GPIO_BASE_ADDR_PQ5
#define BSP_GPIO_BIT_OFFSET_TPQ5   BSP_GPIO_BIT_OFFSET_PQ5
#define BSP_GPIO_BIT_MASK_TPQ5     BSP_GPIO_BIT_MASK_PQ5

#define BSP_GPIO_PORT_ID_TPQ6      BSP_GPIO_PORT_ID_PQ6
#define BSP_GPIO_BASE_ADDR_TPQ6    BSP_GPIO_BASE_ADDR_PQ6
#define BSP_GPIO_BIT_OFFSET_TPQ6   BSP_GPIO_BIT_OFFSET_PQ6
#define BSP_GPIO_BIT_MASK_TPQ6     BSP_GPIO_BIT_MASK_PQ6

#define BSP_GPIO_PORT_ID_LED_G     BSP_GPIO_PORT_ID_PQ7
#define BSP_GPIO_BASE_ADDR_LED_G   BSP_GPIO_BASE_ADDR_PQ7
#define BSP_GPIO_BIT_OFFSET_LED_G  BSP_GPIO_BIT_OFFSET_PQ7
#define BSP_GPIO_BIT_MASK_LED_G    BSP_GPIO_BIT_MASK_PQ7


/**
 * PR0 - TPR0 (J34:35) LCD_CP
 * PR1 - TPR1 (J34:33) LCD_FP
 * PR2 - TPR2 (J34:37) LCD_LP
 * PR3 - TPR3 (J34:23) LCD_DAT3
 * PR4 - TPR4 (J34:17) LCD_DAT0
 * PR5 - TPR5 (J34:19) LCD_DAT1
 * PR6 - TPR6 (J34:25) LCD_DAT4
 * PR7 - TPR7 (J34:27) LCD_DAT5
 */
#define BSP_GPIO_PORT_ID_TPR0      BSP_GPIO_PORT_ID_PR0
#define BSP_GPIO_BASE_ADDR_TPR0    BSP_GPIO_BASE_ADDR_PR0
#define BSP_GPIO_BIT_OFFSET_TPR0   BSP_GPIO_BIT_OFFSET_PR0
#define BSP_GPIO_BIT_MASK_TPR0     BSP_GPIO_BIT_MASK_PR0

#define BSP_GPIO_PORT_ID_TPR1      BSP_GPIO_PORT_ID_PR1
#define BSP_GPIO_BASE_ADDR_TPR1    BSP_GPIO_BASE_ADDR_PR1
#define BSP_GPIO_BIT_OFFSET_TPR1   BSP_GPIO_BIT_OFFSET_PR1
#define BSP_GPIO_BIT_MASK_TPR1     BSP_GPIO_BIT_MASK_PR1

#define BSP_GPIO_PORT_ID_TPR2      BSP_GPIO_PORT_ID_PR2
#define BSP_GPIO_BASE_ADDR_TPR2    BSP_GPIO_BASE_ADDR_PR2
#define BSP_GPIO_BIT_OFFSET_TPR2   BSP_GPIO_BIT_OFFSET_PR2
#define BSP_GPIO_BIT_MASK_TPR2     BSP_GPIO_BIT_MASK_PR2

#define BSP_GPIO_PORT_ID_TPR3      BSP_GPIO_PORT_ID_PR3
#define BSP_GPIO_BASE_ADDR_TPR3    BSP_GPIO_BASE_ADDR_PR3
#define BSP_GPIO_BIT_OFFSET_TPR3   BSP_GPIO_BIT_OFFSET_PR3
#define BSP_GPIO_BIT_MASK_TPR3     BSP_GPIO_BIT_MASK_PR3

#define BSP_GPIO_PORT_ID_TPR4      BSP_GPIO_PORT_ID_PR4
#define BSP_GPIO_BASE_ADDR_TPR4    BSP_GPIO_BASE_ADDR_PR4
#define BSP_GPIO_BIT_OFFSET_TPR4   BSP_GPIO_BIT_OFFSET_PR4
#define BSP_GPIO_BIT_MASK_TPR4     BSP_GPIO_BIT_MASK_PR4

#define BSP_GPIO_PORT_ID_TPR5      BSP_GPIO_PORT_ID_PR5
#define BSP_GPIO_BASE_ADDR_TPR5    BSP_GPIO_BASE_ADDR_PR5
#define BSP_GPIO_BIT_OFFSET_TPR5   BSP_GPIO_BIT_OFFSET_PR5
#define BSP_GPIO_BIT_MASK_TPR5     BSP_GPIO_BIT_MASK_PR5

#define BSP_GPIO_PORT_ID_TPR6      BSP_GPIO_PORT_ID_PR6
#define BSP_GPIO_BASE_ADDR_TPR6    BSP_GPIO_BASE_ADDR_PR6
#define BSP_GPIO_BIT_OFFSET_TPR6   BSP_GPIO_BIT_OFFSET_PR6
#define BSP_GPIO_BIT_MASK_TPR6     BSP_GPIO_BIT_MASK_PR6

#define BSP_GPIO_PORT_ID_TPR7      BSP_GPIO_PORT_ID_PR7
#define BSP_GPIO_BASE_ADDR_TPR7    BSP_GPIO_BASE_ADDR_PR7
#define BSP_GPIO_BIT_OFFSET_TPR7   BSP_GPIO_BIT_OFFSET_PR7
#define BSP_GPIO_BIT_MASK_TPR7     BSP_GPIO_BIT_MASK_PR7


/**
 * PS0 - TPS0 (J31:13)
 * PS1 - TPS1 (J31:19)
 * PS2 - TPS2 (J31:15)
 * PS3 - TPS3 (J31:20)
 * PS4 - TPS4 (J34:29) LCD_DAT6
 * PS5 - TPS5 (J34:31) LCD_DAT7
 * PS6 - TPS6 (J6:8)
 * PS7 - TPS7 (J6:9)
 */
#define BSP_GPIO_PORT_ID_TPS0      BSP_GPIO_PORT_ID_PS0
#define BSP_GPIO_BASE_ADDR_TPS0    BSP_GPIO_BASE_ADDR_PS0
#define BSP_GPIO_BIT_OFFSET_TPS0   BSP_GPIO_BIT_OFFSET_PS0
#define BSP_GPIO_BIT_MASK_TPS0     BSP_GPIO_BIT_MASK_PS0

#define BSP_GPIO_PORT_ID_TPS1      BSP_GPIO_PORT_ID_PS1
#define BSP_GPIO_BASE_ADDR_TPS1    BSP_GPIO_BASE_ADDR_PS1
#define BSP_GPIO_BIT_OFFSET_TPS1   BSP_GPIO_BIT_OFFSET_PS1
#define BSP_GPIO_BIT_MASK_TPS1     BSP_GPIO_BIT_MASK_PS1

#define BSP_GPIO_PORT_ID_TPS2      BSP_GPIO_PORT_ID_PS2
#define BSP_GPIO_BASE_ADDR_TPS2    BSP_GPIO_BASE_ADDR_PS2
#define BSP_GPIO_BIT_OFFSET_TPS2   BSP_GPIO_BIT_OFFSET_PS2
#define BSP_GPIO_BIT_MASK_TPS2     BSP_GPIO_BIT_MASK_PS2

#define BSP_GPIO_PORT_ID_TPS3      BSP_GPIO_PORT_ID_PS3
#define BSP_GPIO_BASE_ADDR_TPS3    BSP_GPIO_BASE_ADDR_PS3
#define BSP_GPIO_BIT_OFFSET_TPS3   BSP_GPIO_BIT_OFFSET_PS3
#define BSP_GPIO_BIT_MASK_TPS3     BSP_GPIO_BIT_MASK_PS3

#define BSP_GPIO_PORT_ID_TPS4      BSP_GPIO_PORT_ID_PS4
#define BSP_GPIO_BASE_ADDR_TPS4    BSP_GPIO_BASE_ADDR_PS4
#define BSP_GPIO_BIT_OFFSET_TPS4   BSP_GPIO_BIT_OFFSET_PS4
#define BSP_GPIO_BIT_MASK_TPS4     BSP_GPIO_BIT_MASK_PS4

#define BSP_GPIO_PORT_ID_TPS5      BSP_GPIO_PORT_ID_PS5
#define BSP_GPIO_BASE_ADDR_TPS5    BSP_GPIO_BASE_ADDR_PS5
#define BSP_GPIO_BIT_OFFSET_TPS5   BSP_GPIO_BIT_OFFSET_PS5
#define BSP_GPIO_BIT_MASK_TPS5     BSP_GPIO_BIT_MASK_PS5

#define BSP_GPIO_PORT_ID_TPS6      BSP_GPIO_PORT_ID_PS6
#define BSP_GPIO_BASE_ADDR_TPS6    BSP_GPIO_BASE_ADDR_PS6
#define BSP_GPIO_BIT_OFFSET_TPS6   BSP_GPIO_BIT_OFFSET_PS6
#define BSP_GPIO_BIT_MASK_TPS6     BSP_GPIO_BIT_MASK_PS6

#define BSP_GPIO_PORT_ID_TPS7      BSP_GPIO_PORT_ID_PS7
#define BSP_GPIO_BASE_ADDR_TPS7    BSP_GPIO_BASE_ADDR_PS7
#define BSP_GPIO_BIT_OFFSET_TPS7   BSP_GPIO_BIT_OFFSET_PS7
#define BSP_GPIO_BIT_MASK_TPS7     BSP_GPIO_BIT_MASK_PS7


/**
 * PT0 - TPT0 (J6:5)
 * PT1 - TPT1 (J6:6)
 * PT2 - TPT2 (J34:9) TOUCH0
 * PT3 - TPT3 (J34:7) TOUCH1
 * PT4 - NCPT4 No Connect
 * PT5 - NCPT5 No Connect
 * PT6 - NCPT6 No Connect
 * PT7 - NCPT7 No Connect
 */
#define BSP_GPIO_PORT_ID_TPT0      BSP_GPIO_PORT_ID_PT0
#define BSP_GPIO_BASE_ADDR_TPT0    BSP_GPIO_BASE_ADDR_PT0
#define BSP_GPIO_BIT_OFFSET_TPT0   BSP_GPIO_BIT_OFFSET_PT0
#define BSP_GPIO_BIT_MASK_TPT0     BSP_GPIO_BIT_MASK_PT0

#define BSP_GPIO_PORT_ID_TPT1      BSP_GPIO_PORT_ID_PT1
#define BSP_GPIO_BASE_ADDR_TPT1    BSP_GPIO_BASE_ADDR_PT1
#define BSP_GPIO_BIT_OFFSET_TPT1   BSP_GPIO_BIT_OFFSET_PT1
#define BSP_GPIO_BIT_MASK_TPT1     BSP_GPIO_BIT_MASK_PT1

#define BSP_GPIO_PORT_ID_TPT2      BSP_GPIO_PORT_ID_PT2
#define BSP_GPIO_BASE_ADDR_TPT2    BSP_GPIO_BASE_ADDR_PT2
#define BSP_GPIO_BIT_OFFSET_TPT2   BSP_GPIO_BIT_OFFSET_PT2
#define BSP_GPIO_BIT_MASK_TPT2     BSP_GPIO_BIT_MASK_PT2

#define BSP_GPIO_PORT_ID_TPT3      BSP_GPIO_PORT_ID_PT3
#define BSP_GPIO_BASE_ADDR_TPT3    BSP_GPIO_BASE_ADDR_PT3
#define BSP_GPIO_BIT_OFFSET_TPT3   BSP_GPIO_BIT_OFFSET_PT3
#define BSP_GPIO_BIT_MASK_TPT3     BSP_GPIO_BIT_MASK_PT3

#define BSP_GPIO_PORT_ID_NCPT4      BSP_GPIO_PORT_ID_PT4
#define BSP_GPIO_BASE_ADDR_NCPT4    BSP_GPIO_BASE_ADDR_PT4
#define BSP_GPIO_BIT_OFFSET_NCPT4   BSP_GPIO_BIT_OFFSET_PT4
#define BSP_GPIO_BIT_MASK_NCPT4     BSP_GPIO_BIT_MASK_PT4

#define BSP_GPIO_PORT_ID_NCPT5      BSP_GPIO_PORT_ID_PT5
#define BSP_GPIO_BASE_ADDR_NCPT5    BSP_GPIO_BASE_ADDR_PT5
#define BSP_GPIO_BIT_OFFSET_NCPT5   BSP_GPIO_BIT_OFFSET_PT5
#define BSP_GPIO_BIT_MASK_NCPT5     BSP_GPIO_BIT_MASK_PT5

#define BSP_GPIO_PORT_ID_NCPT6      BSP_GPIO_PORT_ID_PT6
#define BSP_GPIO_BASE_ADDR_NCPT6    BSP_GPIO_BASE_ADDR_PT6
#define BSP_GPIO_BIT_OFFSET_NCPT6   BSP_GPIO_BIT_OFFSET_PT6
#define BSP_GPIO_BIT_MASK_NCPT6     BSP_GPIO_BIT_MASK_PT6

#define BSP_GPIO_PORT_ID_NCPT7      BSP_GPIO_PORT_ID_PT7
#define BSP_GPIO_BASE_ADDR_NCPT7    BSP_GPIO_BASE_ADDR_PT7
#define BSP_GPIO_BIT_OFFSET_NCPT7   BSP_GPIO_BIT_OFFSET_PT7
#define BSP_GPIO_BIT_MASK_NCPT7     BSP_GPIO_BIT_MASK_PT7
